export const PipelineEvent = {
  PIPELINE_STARTED: 'PIPELINE_STARTED',
  PIPELINE_SUCCESS: 'PIPELINE_SUCCESS',
  PIPELINE_ERROR: 'PIPELINE_ERROR',
  PIPELINE_DUPLICATE: 'PIPELINE_DUPLICATE',
  PIPELINE_INVALID: 'PIPELINE_INVALID',
  PIPELINE_FINISHED: 'PIPELINE_FINISHED'
};

export default PipelineEvent;
