export const ScannerSessionEvent = {
  SESSION_STARTED: 'SESSION_STARTED',
  SESSION_UPDATED: 'SESSION_UPDATED',
  SESSION_FINISHED: 'SESSION_FINISHED',
  SESSION_RESET: 'SESSION_RESET',
  SESSION_ERROR: 'SESSION_ERROR'
};

export default ScannerSessionEvent;
