export const ScannerState = {
  IDLE: 'IDLE',
  INITIALIZING: 'INITIALIZING',
  READY: 'READY',
  DETECTING: 'DETECTING',
  PROCESSING: 'PROCESSING',
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
  COOLDOWN: 'COOLDOWN',
  PAUSED: 'PAUSED',
  STOPPED: 'STOPPED'
};
