export const ScannerEvent = {
  STATE_CHANGED: 'STATE_CHANGED',
  READY: 'READY',
  DETECTING: 'DETECTING',
  PROCESSING: 'PROCESSING',
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
  COOLDOWN: 'COOLDOWN',
  PAUSED: 'PAUSED',
  STOPPED: 'STOPPED',
  DUPLICATED: 'DUPLICATED'
};
