export const ScannerEvents = {
  READY: 'READY',
  STARTED: 'STARTED',
  STOPPED: 'STOPPED',
  DETECTED: 'DETECTED',
  ERROR: 'ERROR',
  TORCH_CHANGED: 'TORCH_CHANGED',
  ZOOM_CHANGED: 'ZOOM_CHANGED',
};
